### ISSUE TITLE
client_test deadlocks

### ISSUE THREAD

**Issue by tzdybal** [dgraph-io/dgraph#1310]
There is some problem with `client_test`, it deadlocks every few runs.

**Comment by tzdybal** [comment]
[client_test_log.txt](https://github.com/dgraph-io/dgraph/files/1199197/client_test_log.txt) - example of deadlock.

**Comment by pawanrawal** [comment]
See this happening on Travis Mac build too. Strangely never seen it happen for Linux build.

**Comment by srh** [comment]
There was a badger deadlock that got fixed with https://github.com/dgraph-io/badger/commit/0dc2cabbf14813542a9ba2e42fcab1c2659581e0.  I would make sure that fix has been vendorized.

I think there is still a Badger deadlock even after that fix, because I recetly killed some runs of "go test ./..." after 180s, when they normally take 50s.  (Not 100% sure because I saw it in my Manifest branch.)

**Comment by tzdybal** [comment]
@srh Unfortunately problem is still visible on `master` after updating badger.

**Comment by tzdybal** [comment]
This is very similar to #1270. Deadlock is related to RAFT processing.
