### ISSUE TITLE
TestQueryTokensPolygon and TestKeyGeneratorPolygon fail under Go 1.9

### ISSUE THREAD

**Issue by srh** [dgraph-io/dgraph#1364]
To reproduce, install Go 1.9 (for example, go1.9.linux-amd64.tar.gz) and run `./test`.  Tests pass after reverting back to Go 1.8.3.

```
--- FAIL: TestQueryTokensPolygon (0.08s)
        Error Trace:    geofilter_test.go:95
	Error:		"[p/4ca4 p/4ca4ac p/4ca4ae4 p/4ca4b94 p/4ca4bc p/4ca4bec p/4ca4bf p/4ca4b p/4cbb4c p/4cbb4d4 p/4ca5 p/4ca4af p/4ca4bd p/4ca4c p/4ca4bc804 p/4cbb5 p/4cbb p/4ca4a4d p/4ca4a5 p/4ca4ad4 p/4ca4ad p/4ca4b7 p/4ca4b9c p/4ca4bb p/4ca4bc81 p/4ca4a4c p/4cbc p/4ca4bcc p/4ca4adc p/4ca4ae3 p/4ca4b3 p/4ca4b6c p/4ca4b9 p/4ca4beb p/4ca4a4 p/4ca4bc4 p/4ca4bc84 p/4cbb4d p/4cbb4 p/4ca4b74 p/4ca4ae1 p/4ca4ae24 p/4ca4b44 p/4cbb4d5 p/4ca4a54 p/4ca4b4 p/4ca4b5 p/4ca4bc9 p/4ca4b1 c/4ca4a4d c/4ca4a54 c/4ca4ad4 c/4ca4adc c/4ca4ae1 c/4ca4ae24 c/4ca4b1 c/4ca4b3 c/4ca4b44 c/4ca4b6c c/4ca4b74 c/4ca4b94 c/4ca4b9c c/4ca4bb c/4ca4bc4 c/4ca4bc804 c/4ca4beb c/4cbb4d5]" should have 66 item(s), but has 67
		
--- FAIL: TestKeyGeneratorPolygon (0.06s)
        Error Trace:    s2index_test.go:150
	Error:		"[p/4ca4bc84 p/4ca4beb p/4ca4b3 p/4ca4b44 p/4ca4b6c p/4ca4b9 p/4ca4bc9 p/4ca4bec p/4ca4bf p/4cbb4d p/4ca4ae4 p/4ca4ae3 p/4ca4b5 p/4ca4b7 p/4ca4bb p/4ca4bcc p/4ca4a5 p/4ca5 p/4ca4adc p/4ca4ae1 p/4ca4b94 p/4ca4bc p/4ca4bc804 p/4cbb4d4 p/4ca4a54 p/4ca4af p/4ca4b4 p/4ca4b74 p/4cbb5 p/4cbb4 p/4ca4b p/4ca4ae24 p/4ca4bc4 p/4ca4bc81 p/4ca4b1 p/4ca4bd p/4cbb4d5 p/4ca4a4 p/4ca4c p/4ca4ad4 p/4ca4ac p/4ca4b9c p/4cbb4c p/4cbb p/4cbc p/4ca4a4d p/4ca4a4c p/4ca4 p/4ca4ad c/4ca4a4d c/4ca4a54 c/4ca4ad4 c/4ca4adc c/4ca4ae1 c/4ca4ae24 c/4ca4b1 c/4ca4b3 c/4ca4b44 c/4ca4b6c c/4ca4b74 c/4ca4b94 c/4ca4b9c c/4ca4bb c/4ca4bc4 c/4ca4bc804 c/4ca4beb c/4cbb4d5]" should have 66 item(s), but has 67
		
FAIL
FAIL	github.com/dgraph-io/dgraph/types	0.851s
```

**Comment by pawanrawal** [comment]
Having a look.

**Comment by srh** [comment]
Fixed by Pawan with (I think) dc1948fb9b9573ecd9800546bf46e3aa6063059e.

**Comment by pawanrawal** [comment]
No, that doesn't fix it. I have opened an issue [here](https://github.com/golang/geo/issues/30) and am following up. It's not a big issue I suppose but I want to verify it.

**Comment by srh** [comment]
My bad.  Confirmed still not working.  Maybe I just ran `go build` and didn't run tests, or something like that, even though I thought I had.

**Comment by pawanrawal** [comment]
I don't think we need to sweat over this. I visualized the regions covered by the cell and they are indistinguishable. Will change the output of the tests and then we can move to v1.9.

**Comment by pawanrawal** [comment]
Modified the test results and merged to master. We can move to Go 1.9.
