### ISSUE TITLE
dgraph ratel visualizer colors inacurate

### ISSUE THREAD

**Issue by aryzing** [dgraph-io/dgraph#1967]
While going through the tutorial, I realized that the ratel visualizer colors are off, see image

![](https://user-images.githubusercontent.com/4924405/34387959-6d224cd2-eb31-11e7-9169-9d23cc1e6405.png)

Happens both in docker version and well as in https://play.dgraph.io

**Comment by gpahal** [comment]
Fixed the issue. It should be reflected in the next dev build.

**Comment by pawanrawal** [comment]
@gpahal Can still see it on `https://play.dgraph.io` which has `v1.0.2` deployed.

Try this query

```
{
  me(func: eq(name@en, "Steven Spielberg")) {
    name@en
    director.film {
      name@en
      genre {
        name@en
      }
    }
  }
}
```

and notice how the colours of the label don't match the colour of the nodes.

**Comment by gpahal** [comment]
I did not push the changes. Now, it's working.

**Comment by aryzing** [comment]
Not sure if this bug might have crept back in, colors seem to be innacurate again:

![dgraph-colors](https://user-images.githubusercontent.com/4924405/38166132-ed4c227a-351e-11e8-8b37-8d0fc75496eb.png)

FYI-1: I'm on v1.0.3
FYI-2: "Jeunet" is Jean-Pierre's last name
