### ISSUE TITLE
SI violation with node crashes or predicate moves in bank tests

### ISSUE THREAD

**Issue by aphyr** [dgraph-io/dgraph#2321]
In healthy clusters, with @upsert schema directives on `key` and `type` attributes (but not on values), and server-side ordering set for all client transactions, version

```
Dgraph version   : v1.0.4
Commit SHA-1     : 6fb69e2
Commit timestamp : 2018-04-09 21:26:31 +0530
Branch           : jan/node_lockup
```

can exhibit a violation of snapshot isolation, allowing account values to drift higher or lower over time. This may be related to #2143 (the previous bank test failure without any nemesis, now closed), but I suspect this issue miiight be different than #2290, where documents are lost or have `nil` values instead of their correct data, because that would cause an *undercount*, and in bank tests, I can also observe *overcounting*. For instance, in [20180409T163239.000-0500.zip](https://github.com/dgraph-io/dgraph/files/1892343/20180409T163239.000-0500.zip):

```
9	:invoke	:transfer	{:from 1, :to 3, :amount 2}
8	:ok	:read	{0 43, 1 4, 2 3, 3 3, 4 10, 5 7, 6 27, 7 3}
8	:invoke	:transfer	{:from 2, :to 6, :amount 4}
6	:fail	:transfer	{:from 7, :to 4, :amount 1}	:conflict
6	:invoke	:read	nil
3	:fail	:transfer	{:from 5, :to 7, :amount 1}	:conflict
3	:invoke	:read	nil
4	:ok	:read	{0 43, 1 4, 2 3, 3 3, 4 10, 5 7, 6 27, 7 3}
4	:invoke	:read	nil
2	:ok	:read	{0 43, 1 4, 2 5, 3 3, 4 10, 5 7, 6 25, 7 3}
6	:ok	:read	{0 43, 1 4, 2 3, 3 4, 4 10, 5 7, 6 27, 7 2}
2	:invoke	:read	nil
6	:invoke	:read	nil
6	:ok	:read	{0 43, 1 4, 2 3, 3 4, 4 10, 5 7, 6 27, 7 2}
6	:invoke	:read	nil
4	:ok	:read	{0 43, 1 4, 2 3, 3 4, 4 10, 5 7, 6 27, 7 2}
4	:invoke	:read	nil
3	:ok	:read	{0 43, 1 4, 2 3, 3 4, 4 10, 5 7, 6 27, 7 2}
3	:invoke	:read	nil
8	:fail	:transfer	{:from 2, :to 6, :amount 4}	:insufficient-funds
8	:invoke	:transfer	{:from 4, :to 7, :amount 5}
0	:ok	:transfer	{:from 1, :to 6, :amount 2}
0	:invoke	:read	nil
6	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
6	:invoke	:read	nil
5	:fail	:transfer	{:from 1, :to 7, :amount 3}	:conflict
5	:invoke	:read	nil
1	:fail	:transfer	{:from 6, :to 2, :amount 2}	:conflict
1	:invoke	:transfer	{:from 6, :to 2, :amount 2}
0	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
3	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
0	:invoke	:transfer	{:from 2, :to 0, :amount 2}
3	:invoke	:transfer	{:from 7, :to 1, :amount 4}
5	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
4	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
5	:invoke	:read	nil
4	:invoke	:transfer	{:from 6, :to 5, :amount 3}
2	:ok	:read	{0 43, 1 4, 2 3, 3 4, 4 10, 5 7, 6 27, 7 2}
2	:invoke	:read	nil
5	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
6	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
5	:invoke	:read	nil
6	:invoke	:read	nil
5	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
5	:invoke	:transfer	{:from 1, :to 0, :amount 5}
6	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
6	:invoke	:transfer	{:from 1, :to 3, :amount 5}
9	:ok	:transfer	{:from 1, :to 3, :amount 2}
9	:invoke	:transfer	{:from 0, :to 2, :amount 2}
0	:ok	:transfer	{:from 2, :to 0, :amount 2}
0	:invoke	:transfer	{:from 3, :to 5, :amount 5}
5	:fail	:transfer	{:from 1, :to 0, :amount 5}	:insufficient-funds
5	:invoke	:read	nil
2	:ok	:read	{0 43, 1 2, 2 3, 3 4, 4 10, 5 7, 6 29, 7 2}
2	:invoke	:transfer	{:from 0, :to 2, :amount 2}
6	:fail	:transfer	{:from 1, :to 3, :amount 5}	:insufficient-funds
6	:invoke	:transfer	{:from 1, :to 2, :amount 5}
5	:ok	:read	{0 45, 1 2, 2 1, 3 6, 4 10, 5 7, 6 29, 7 2}
```

Here, the final read has a total of 102: 2 has been transferred from account 2 to account 0, but account 3 has also *gained* 2 out of nowhere. The only recent increment of account 3 comes from process 9's transfer of 2 from 1 to 3, but it doesn't appear to have applied atomically?

These don't appear to just be read-only anomalies; they can be promoted via writes back into the database state--the value remains 102 for the remainder of the test.

You can reproduce this with Jepsen 0ef6e711dfb07aad4afc84f7f9c3348961afa9d7 by running

```
lein run test --package-url https://transfer.sh/Z5CTJ/dgraph-linux-amd64.tar.gz --time-limit 300 --concurrency 2n --nemesis kill-alpha,fix-alpha,kill-zero --test-count 20 --workload bank --upsert-schema
```

**Comment by aphyr** [comment]
I've collected a bit more evidence here. These plots show the observed sum of accounts over time, and colors represent the different nodes being queried. In a snapshot isolated system, the numbers always be 100. In some runs, the value periodically jumps to n+d, then returns to n for a time, then goes back to n+d, and so on--this feels like it could be a read skew anomaly that wasn't promoted via a write. In this test, the anomalous total was the same *each time*, and visible across multiple nodes. I'm not sure what to make of this.

![bank](https://user-images.githubusercontent.com/3748/38576771-b2c3d0dc-3cc4-11e8-8553-3e7133377adc.png)

A more understandable plot looks like this:

![bank](https://user-images.githubusercontent.com/3748/38576773-b3bd7826-3cc4-11e8-8491-a95f8d49b321.png)

Here, we see a period where accounts drift lower, then they start drifting higher again. The semi-contiguous, fuzzy nature of the distribution feels consistent with read skews being propagated back into write transactions, causing the value to drift over time. I'm not sure what to make of the steady trends down and up, though--this doesn't exactly look like a random walk to me. I wonder if perhaps a single account which has a chance of going missing, or appearing as an extra account, in some reads might cause a linear drift in the mean value over time?

**Comment by aphyr** [comment]
I've managed to narrow this down to crashes with just alpha--it doesn't require a zero crash to reproduce.

**Comment by aphyr** [comment]
OK, we can also reproduce this problem with no crashes and just network partitions, and it turns out there's a weird thing occurring I didn't think to check for--some reads include objects with *no* key! Take a look at this:

```
      :value {nil 3, 0 1, 1 15, 2 18, 3 5, 4 9, 5 17, 6 23, 7 12},
```

We have a value for all 8 keys here, plus one we *didn't* expect: a blank key with the value 3. The 8 normal keys sum to 100, but the blank key raises the total to 103. This looks like it might be related to the blank records we got for queries in #2290?

**Comment by aphyr** [comment]
OK, cool. Dgraph will actually do this in healthy clusters, you just have to wait long enough. Here's a history with no crashes or partitions at all, where the sum of accounts is fine, fine, fine, then fluctuates wildly, dropping to less than 10% of its expected value at one point.
![bank](https://user-images.githubusercontent.com/3748/38595638-93050b14-3d12-11e8-9154-29f3d333c535.png)

[20180410T223952.000-0500.zip](https://github.com/dgraph-io/dgraph/files/1897219/20180410T223952.000-0500.zip)

You can reproduce this with Jepsen 30c37d64f92ad2864e27ed6b818bf33e633a94be:

```
lein run test --package-url https://transfer.sh/Z5CTJ/dgraph-linux-amd64.tar.gz --time-limit 600 --concurrency 2n --nemesis none --test-count 20 --workload bank --upsert-schema
```

**Comment by aphyr** [comment]
Another run-here, we're OK until about 461 seconds in, when latency drops *dramatically* and we start getting a slew of errors. Reads return things like:

```
     {:type :ok,
      :f :read,
      :process 3,
      :time 460996049202,
      :value {0 nil, 1 nil, 2 4, 3 nil, 4 nil, 5 nil, 6 nil},
```

... for a query for all records of type "account". We never create accounts without a value (or a key, for that matter), so these are clearly illegal.

Around the same time we start seeing these nil requests, we get a handful of errors like

```
io.grpc.StatusRuntimeException: UNKNOWN: : rpc error: code = Unknown desc = Temporary error, attr: "amount" groupId: 2 Request sent to wrong server
```
and

```
io.grpc.StatusRuntimeException: UNKNOWN: : Tablet isn't being served by this instance.
```

And about thirty `Predicate is being moved, please retry later` errors. That makes me suspect that maybe predicate/tablet migrations are involved here?

**Comment by aphyr** [comment]
Nothing particularly new here, but this plot suggest the characteristic behaviors we've identified in account sums (sloping, jumping between two values, and fuzzily bouncing all over the place) are separable phenomena, although each is associated with a tablet move. [20180416T111943.000-0500.zip](https://github.com/dgraph-io/dgraph/files/1916469/20180416T111943.000-0500.zip)

![bank](https://user-images.githubusercontent.com/3748/38825224-663b2916-4171-11e8-826b-6604b188b346.png)

**Comment by aphyr** [comment]
You can now reproduce these problems significantly faster in Jepsen eb796cfcc204c592545965968bd28ad1e6b2eff0 by using the `move-tablet` nemesis, which shuffles tablets around every 15 seconds or so.

```
lein run test --package-url https://github.com/dgraph-io/dgraph/releases/download/nightly/dgraph-linux-amd64.tar.gz --time-limit 60 --concurrency 1n --nemesis move-tablet --workload bank --upsert-schema
```

**Comment by janardhan1993** [comment]
Some of the issue are fixed in #2339

**Comment by manishrjain** [comment]
This might also be fixed by #2392 . Testing it.

**Comment by manishrjain** [comment]
I have to run the test for half an hour, before this happens, but I see a `nil` key being added. Not sure if this is due to predicate move, or something else.

```
 {:valid? false,
   :read-count 21882,
   :error-count 1427,
   :first-error
   {:type :unexpected-key,
    :unexpected (nil),
    :op
    {:type :ok,
     :f :read,
     :process 52,
     :time 1153593764746,
     :value {nil 2, 0 23, 1 18, 2 17, 3 2, 5 24, 6 6, 7 10},
     :index 58951}},
```

**Comment by aphyr** [comment]
Yeah, it looks like we're still seeing violations in the binary you sent over on 2018-05-16 (it doesn't log any version info so I'm not exactly sure what code was in it). They're less frequent now! It took a couple hours before I hit this case: [20180516T194304.000-0500.zip](https://github.com/dgraph-io/dgraph/files/2013028/20180516T194304.000-0500.zip)

In this case, we never observed nil keys, but it looks like we abruptly lost about half the keys in the database--keys 2, 3, 4, 5, and 7 vanished.

```clj
{:type :invoke, :f :read, :process 7, :time 80842565886, :index 2017}
{:type :ok, :f :read, :process 5, :time 80997241014, :value {0 31, 1 15, 2 15, 3 7, 4 16, 5 2, 6 8, 7 6}, :index 2018}
{:type :invoke, :f :transfer, :value {:from 2, :to 1, :amount 3}, :process 5, :time 80997495741, :index 2019}
{:type :ok, :f :read, :process 7, :time 81175273547, :value {0 31, 1 15, 5 2, 6 8}, :index 2020}
```

It looks like these errors are persistent--they affect all nodes and are semi-stable over time.

![bank 3](https://user-images.githubusercontent.com/3748/40176550-c0416394-59a9-11e8-9605-7fc287ecacec.png)

**Comment by manishrjain** [comment]
Testing this right now, let's see.

**Comment by aphyr** [comment]
Testing the build you sent on Friday, we're still seeing divergence every ~5000 seconds with predicate moves. In [20180522T110600.000-0500.zip](https://github.com/dgraph-io/dgraph/files/2027603/20180522T110600.000-0500.zip), the value diverged in what sort of looks like a split-brain scenario:

![bank 4](https://user-images.githubusercontent.com/3748/40376440-f4572660-5db3-11e8-9370-946991c38a6b.png)

You can reproduce this on Jepsen 789103bfd25f8635ed3410a38237003b0ae45da1 with

```
lein run test --local-binary ~/tmp/dgraph --force-download --nemesis move-tablet --sequencing server --upsert-schema --time-limit 300 --concurrency 1n --nemesis-interval 5 --workload bank --retry-db-setup --test-count 10
```

**Comment by manishrjain** [comment]
I'm trying out bank tests with predicate moves disabled. Want to determine if this problem is only due to moves, or it happens without the moves as well.

**Comment by manishrjain** [comment]
Alright. Long time! So, I've fixed all the txn violations in a cluster, with tablet moves not happening. That's already done.

With the tablet move, I've simplified the design that we had in place before significantly, with this change: https://github.com/dgraph-io/dgraph/commit/63f81741f83a20547f123f625cc3623cede983d4

With this change, say a tablet moves from group X to group Y, and the write for a tablet P was made on the older group X. When commit goes to Zero, it would assert that P belongs to Y, and that the write should have been to Y; and reject that transaction. This ensures that during tablet moves, any write transaction would provide ACID guarantees.

However, this mechanism can still let a few reads go through to the older group X, which is holding stale data, hence causing some failures in Jepsen reads.

The reason is that membership information of tablets and the groups serving them, flows via Zero leader to the Alphas. This flow isn't being deterministically transmitted via Raft, instead, it happens on a continuous basis, via direct connections to Zero. Therefore, it is possible that some Alpha could be behind in the knowledge that a certain tablet has been moved from X to Y group. In that case, this Alpha could still serve some reads directly. But, any writes on that Alpha would be denied commit by Zero, as described above.

These few spurious reads are what we see in the graphs below. But, apart from a few stale reads, the total does not permanently deviate from the intended 100.

![bank0](https://user-images.githubusercontent.com/1782324/51364257-68f4d780-1a90-11e9-8ac6-b2e3d09701f1.png)
![bank1](https://user-images.githubusercontent.com/1782324/51364259-6abe9b00-1a90-11e9-847c-d52b072741a3.png)
![bank2](https://user-images.githubusercontent.com/1782324/51364264-6e522200-1a90-11e9-9412-ea123b176a21.png)

Any more checks to avoid such a read would only come at the cost of performance, without major benefits. Tablet moves are meant to be rare, not as commonly as Jepsen test runs them; so I think the mechanisms that we have in place are sufficient for almost all users.

And if there are certain use cases which need these reads to be rejected, we could consider putting something harder in place, at the cost of performance. But, for now, I think this is good.

**Comment by manishrjain** [comment]
Solved!

> However, this mechanism can still let a few reads go through to the older group X, which is holding stale data, hence causing some failures in Jepsen reads.

I introduced group checksums, which get propagated along with txn status information. Using that, any Alpha would now know if the membership has changed at Zero, but not yet propagated to itself yet, and would block replying until it does. This and some other rare edge case issues are resolved in my PR above. This ticks off the official last major Jepsen issue.

Started looking at these Jepsen issues in May 2018, not full time of course, but on and off. Needed an almost redesign of the entire flow of transactions and data in Dgraph. What a journey! This PR largely concludes Dgraph v1.0 series (future versions would be v1.1).

![2019-02-01-145044_1011x764_scrot](https://user-images.githubusercontent.com/1782324/52153981-e8f27400-2630-11e9-9fed-e320932207f2.png)
