### ISSUE TITLE
ICU_DATA breaks Java on OSX

### ISSUE THREAD

**Issue by nlothian** [dgraph-io/dgraph#491]
After installing the ICU data on OSX following the instructions at https://wiki.dgraph.io/Deploy#String_indexing Java stopped working with the following error:

`~ java`

` 2017-01-16 14:29:16.193 java[1110:14026] [JVM Detection] FillMatcher: failed to create CFNumberFormatter`

Un-setting the ICU_DATA environment variable fixes the problem.

**Comment by jchiu0** [comment]
Related issue: https://github.com/dgraph-io/dgraph/issues/429

I would have to revert the changes for #429 and look into why it doesn't work for the embedded binary.

**Comment by jchiu0** [comment]
Give it a try. It should be fixed now. Be sure to pull the latest from dgraph-io/goicu.

**Comment by jtblin** [comment]
> Give it a try. It should be fixed now. Be sure to pull the latest from dgraph-io/goicu.

What does that mean exactly? I still have the issue with the latest dgraph-io/goicu. I have an environment variable set as `export ICU_DATA=/usr/local/share/icudt58l.dat` from a previous installation I guess so I'm not too sure. Unsetting the environment variable seems to be the only way to fix that right now. Is that expected?

**Comment by pawanrawal** [comment]
Hi @jtblin 

As of v0.7.3, you don't need to set the ICU_DATA environment variable. You can unset it. Make sure to install the latest version using https://wiki.dgraph.io/Get_Started#System_Installation and let us know if something doesn't work.

**Comment by jtblin** [comment]
OK, thanks. Yes I've removed the environment variable, I guess it was from an old installation.

**Comment by manishrjain** [comment]
Note that from the coming release, we would get rid of ICU in favor of Bleve, which would work without any of these env variable hacks.
